[package]
name = "starkli"
version = "0.0.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Starkli (/ˈstɑːrklaɪ/), a blazing fast CLI tool for StarkNet powered by starknet-rs"

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.23"
clap = { version = "4.0.26", features = ["derive", "env"] }
clap_complete = "4.0.5"
colored = "2.0.0"
colored_json = "3.0.1"
regex = "1.7.0"
serde_json = { version = "1.0.89", features = ["preserve_order"] }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
tokio = { version = "1.22.0", default-features = false, features = ["macros", "rt-multi-thread"] }
url = "2.3.1"
