[package]
name = "starkli"
version = "0.0.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = """
Starkli (/ˈstɑːrklaɪ/), a blazing fast CLI tool for StarkNet powered by starknet-rs
"""

[dependencies]
